//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages.AiImageCheck {


	public partial class AnlItemInput {

		/// <summary>
		/// lblItemCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblItemCd;

		/// <summary>
		/// txtItemNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtItemNm;

		/// <summary>
		/// lblLineNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblLineNm;

		/// <summary>
		/// lblStationNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblStationNm;

		/// <summary>
		/// ddlUsingTool control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlUsingTool;

		/// <summary>
		/// txtStream control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtStream;

		/// <summary>
		/// txtUsingModel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtUsingModel;

		/// <summary>
		/// txtExpectResult control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtExpectResult;

		/// <summary>
		/// btnUpdate control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnUpdate;

		/// <summary>
		/// ktbtnClose control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton ktbtnClose;

		/// <summary>
		/// resultText control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox resultText;

		/// <summary>
		/// divLoadingData control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::TRC_W_PWT_ProductView.UI.Pages.UserControl.LoadingData divLoadingData;
	}
}
