//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages.AiImageCheck {


	public partial class MainCorrectiveView {

		/// <summary>
		/// upnCondition control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.UpdatePanel upnCondition;

		/// <summary>
		/// ddlLineCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlLineCd;

		/// <summary>
		/// ddlStation control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlStation;

		/// <summary>
		/// txtModelNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtModelNm;

		/// <summary>
		/// txtModelCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtModelCd;

		/// <summary>
		/// txtKiban control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtKiban;

		/// <summary>
		/// txtIdno control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtIdno;

		/// <summary>
		/// txtMonthlySeqNum control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtMonthlySeqNum;

		/// <summary>
		/// ddlAnlResult control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlAnlResult;

		/// <summary>
		/// cldStart control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldStart;

		/// <summary>
		/// cldEnd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldEnd;

		/// <summary>
		/// btnSearch control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnSearch;

		/// <summary>
		/// pnlPager control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel pnlPager;

		/// <summary>
		/// ntbResultCount control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTNumericTextBox ntbResultCount;

		/// <summary>
		/// divGrvDisplay control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvDisplay;

		/// <summary>
		/// divGrvHeaderLT control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvHeaderLT;

		/// <summary>
		/// grvDetailHeaderLT control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvDetailHeaderLT;

		/// <summary>
		/// divGrvLB control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvLB;

		/// <summary>
		/// grvDetailBodyLB control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvDetailBodyLB;

		/// <summary>
		/// btnViewRefresh control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnViewRefresh;

		/// <summary>
		/// InputModal1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::TRC_W_PWT_ProductView.UI.Pages.UserControl.InputModal InputModal1;
	}
}
