//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages.AiImageCheck {


	public partial class MainCorrectiveInput {

		/// <summary>
		/// lblAnlResult control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblAnlResult;

		/// <summary>
		/// lblImgAnlItemNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblImgAnlItemNm;

		/// <summary>
		/// lblCorrectiveResult control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblCorrectiveResult;

		/// <summary>
		/// ddlNgType control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlNgType;

		/// <summary>
		/// ddlCorrectiveType control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlCorrectiveType;

		/// <summary>
		/// txtCorrectiveComment control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox txtCorrectiveComment;

		/// <summary>
		/// lblUpdateBy control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblUpdateBy;

		/// <summary>
		/// lblThisTimeUpdateBy control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Label lblThisTimeUpdateBy;

		/// <summary>
		/// btnUpdate control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnUpdate;

		/// <summary>
		/// ktbtnClose control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton ktbtnClose;
	}
}
